---
- hosts: all
  roles:
    - role: SimpliField.users
      users:
        - name: "simplifield"
          comment: "simplifield user"
          createhome: "yes"
          home: "/home/simplifield"
          shell: "/bin/false"
